Source/AirlinesReservationSystem/AirlinesReservationSystem/Models/Flight.cs
namespace AirlinesReservationSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            
            this.Prices = new HashSet<Price>();
            
            this.DiscountDetails = new HashSet<DiscountDetail>();
            this.Booking_Ticket = new HashSet<Booking_Ticket>();
            this.SeatDetailByFlights = new HashSet<SeatDetailByFlight>();
        }
        public int Flightid { get; set; }

        public int RouterId { get; set; }

        public DateTime Dept_Time { get; set; }

        public DateTime Arr_Time { get; set; }

        public int? Status { get; set; }

        public int PlaneId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Prices { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountDetail> DiscountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Ticket> Booking_Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatDetailByFlight> SeatDetailByFlights { get; set; }
        public virtual Plane Plane { get; set; }
        public virtual Router Router { get; set; }
        
    }
}

Source/AirlinesReservationSystem/AirlinesReservationSystem/ViewModels/FlightViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.ComponentModel;
using AirlinesReservationSystem.ValidationAtributesCustom;

namespace AirlinesReservationSystem.ViewModels
{
    public class FlightViewModel
    {
        [Key]
        public int FlightID { get; set; }
       // public int LocationId { get; set; }
        [Required]
        public int Location_Depart { get; set; }
        [Required]
       // [Compare("Location_Depart" , ErrorMessage = "The Depart and Arrival do not match.")]
        public int Location_Arrival { get; set; }
        [Required]
        public DateTime Time_Depart { get; set; }

        [RequiredIf("Trip", "Round", "Requied If you choosed Round")]
        public DateTime? Time_Arrival { get; set; }
        [Required]
        public string Trip { get; set; }
        [Range(1,3)][Required]
        public int Adults { get; set; }
    }
}

Source/AirlinesReservationSystem/AirlinesReservationSystem/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AirlinesReservationSystem;
using AirlinesReservationSystem.ViewModels;

namespace AirlinesReservationSystem.Controllers
{
    public class FlightsController : Controller
    {
        private Areas.Admin.ReponsitoryModel.ReponsitoryFlights reponsitoryFlights = new Areas.Admin.ReponsitoryModel.ReponsitoryFlights();
        private Areas.Admin.ReponsitoryModel.ReponsitoryLocations reponsitoryLocation = new Areas.Admin.ReponsitoryModel.ReponsitoryLocations();
        private Areas.Admin.ReponsitoryModel.ReponsitorySeatDetailByFlight reponsitorySeatDetailByFlight = new Areas.Admin.ReponsitoryModel.ReponsitorySeatDetailByFlight();
        private Areas.Admin.ReponsitoryModel.ReponsitorySeatClass _Seatclass = new Areas.Admin.ReponsitoryModel.ReponsitorySeatClass();
        private Areas.Admin.ReponsitoryModel.ReponsitoryPrices _price = new Areas.Admin.ReponsitoryModel.ReponsitoryPrices();
        private Areas.Admin.ReponsitoryModel.ReponsitoryQuantitySeatClass _quantitySeat = new Areas.Admin.ReponsitoryModel.ReponsitoryQuantitySeatClass();
        private Areas.Admin.ReponsitoryModel.ReponsitoryBookingTicket _booking = new Areas.Admin.ReponsitoryModel.ReponsitoryBookingTicket();
        private Areas.Admin.ReponsitoryModel.ReponsitoryDiscountDetail _Discount = new Areas.Admin.ReponsitoryModel.ReponsitoryDiscountDetail();
        //Get : Flights
        public ActionResult Index()
        {
            TempData["DataDepart"] = new SelectList(reponsitoryLocation.SelectAll(), "LocationId", "City");
            TempData["DataArrival"] = new SelectList(reponsitoryLocation.SelectAll(), "LocationId", "City");

            return Redirect("Home/index");
            //return PartialView("_SearchFlight");
        }

        // Post: Flights ([Bind(Include = "Flightid,RouterId,Dept_Time,Arr_Time,Status,PlaneId")] Flight flight)
        [HttpPost]
        public ActionResult Index([Bind(Include = "FlightID,Location_Depart,Location_Arrival,Time_Depart,Time_Arrival,Trip,Adults")] FlightViewModel flightVm)
        {
            if (!ModelState.IsValid)
            {
                TempData["DataDepart"] = new SelectList(reponsitoryLocation.SelectAll(), "LocationId", "City");
                TempData["DataArrival"] = new SelectList(reponsitoryLocation.SelectAll(), "LocationId", "City");
                return View("~/Views/Home/Index.cshtml");
            }
            //Get Depart Flights
            var flight = reponsitoryFlights.SelectAll();
            var flightdepart = flight
                .Where(x => x.Dept_Time.CompareTo(flightVm.Time_Depart) > 0 && x.Dept_Time.CompareTo(DateTime.Now) > 0)
                .Where(x => x.Router.AirportDepart.Location.LocationId == flightVm.Location_Depart)
                .Where(x => x.Router.AirportArrival.Location.LocationId == flightVm.Location_Arrival)
                .ToList();
            if (flightdepart.Count == 0)
            {
                return View("NotHaveFlight");
            }
            else
            {
                //Get Seat Class
                var seatclasses = _Seatclass.SelectAll();
                ViewBag.SeatClass = new List<SeatClass>();
                ViewBag.SeatClass = seatclasses;

                //Get Inventory seat by Seat Class and Flight
                List<InventoryTickets> inventories = new List<InventoryTickets>();
                foreach (var flightdep in flightdepart)
                {
                    foreach (var seatclass in seatclasses)
                    {
                        InventoryTickets inventory = new InventoryTickets
                        {
                            FlightId = flightdep.Flightid,
                            SeatClassId = seatclass.SeatClassId
                        };
                        QuantitySeatClass seat = new QuantitySeatClass();
                        seat = _quantitySeat.SelectAll().Where(x => x.PlaneId == flightdep.PlaneId).Where(x => x.SeatClassId == seatclass.SeatClassId).FirstOrDefault();
                        int countBooking = _booking.SelectAll().Where(x => x.FlightId == flightdep.Flightid).Where(x => x.SeatClassId == seatclass.SeatClassId).Where(x => x.ReservationModId == 1 || x.ReservationModId == 2).Count();
                        inventory.Inventory = (seat.Quantity - countBooking);
                        inventories.Add(inventory);
                    }

                }

                //var seatnumber = _seatnumber.SelectAll();
                ViewBag.Inventories = inventories;

                //Get Price
                var Price = _price.SelectAll();
                ViewBag.Price = new List<Price>();
                ViewBag.Price = Price;
                //Get Discount
                var Discount = _Discount.SelectAll();
                ViewBag.Discount = new List<DiscountDetail>();
                ViewBag.Discount = Discount;
                TempData["Adults"] = flightVm.Adults;
                //Get Arrival Flight
                if (flightVm.Trip == "Round")
                {
                    var flightarival = flight
                    .Where(x => x.Dept_Time.CompareTo(flightVm.Time_Arrival) > 0 && x.Dept_Time.CompareTo(DateTime.Now) > 0)
                    .Where(x => x.Router.AirportDepart.Location.LocationId == flightVm.Location_Arrival)
                    .Where(x => x.Router.AirportArrival.Location.LocationId == flightVm.Location_Depart)
                    .ToList();
                    ViewBag.FlightArrival = new List<Flight>();
                    ViewBag.FlightArrival = flightarival;
                    List<InventoryTickets> inventoriesArr = new List<InventoryTickets>();
                    foreach (var flightdep in flightarival)
                    {
                        foreach (var seatclass in seatclasses)
                        {
                            InventoryTickets inventoryArr = new InventoryTickets
                            {
                                FlightId = flightdep.Flightid,
                                SeatClassId = seatclass.SeatClassId
                            };
                            QuantitySeatClass seat = new QuantitySeatClass();
                            seat = _quantitySeat.SelectAll().Where(x => x.PlaneId == flightdep.PlaneId).Where(x => x.SeatClassId == seatclass.SeatClassId).FirstOrDefault();
                            int countBooking = _booking.SelectAll().Where(x => x.FlightId == flightdep.Flightid).Where(x => x.SeatClassId == seatclass.SeatClassId).Where(x => x.ReservationModId == 1 || x.ReservationModId == 2).Count();
                            inventoryArr.Inventory = (seat.Quantity - countBooking);
                            inventoriesArr.Add(inventoryArr);
                        }

                    }

                    //var seatnumber = _seatnumber.SelectAll();
                    TempData["InventoriesArr"] = inventoriesArr;
                }
            }
           
            return View(flightdepart);

        }

        public ActionResult ArrivalFlight()
        {
            if (ViewBag.FlightArrival == null)
            {
                return View("NotHaveFlight");
            }
            else
            {
                string FlightID = Request.QueryString["FlightId"];
                string SeatClassID = Request.QueryString["SeatClassId"];
                TempData["DepartFlight"] = TempData["Depart" + FlightID + SeatClassID];

                var seatclass = _Seatclass.SelectAll();
                ViewBag.SeatClass = new List<SeatClass>();
                ViewBag.SeatClass = seatclass;

                var Price = _price.SelectAll();
                ViewBag.Price = new List<Price>();
                ViewBag.Price = Price;

                var Discount = _Discount.SelectAll();
                ViewBag.Discount = new List<DiscountDetail>();
                ViewBag.Discount = Discount;

                
            }
            return View();
        }
    }
}

Source/AirlinesReservationSystem/AirlinesReservationSystem/Views/Flights/Index.cshtml
@model IEnumerable<AirlinesReservationSystem.Flight>

@{
                /**/

                ViewBag.Title = "Depart Flight";
                Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="limiter">
    <div class="container-table100">
        <div class="wrap-table100">
            <div class="table100">
                <h3 style="color:white">Flight Depart</h3>
                <table>
                    <thead>
                        <tr class="table100-head">
                            <th class="column1">Plane</th>
                            <th class="column2">Router</th>
                            <th class="column3">Departing</th>
                            <th class="column4">Returning</th>
                            @{
                                List<SeatClass> seatClasses = new List<SeatClass>();
                                seatClasses = ViewBag.SeatClass;
                                int clNumber = 5;
                                string clName = "column";
                                foreach (var i in seatClasses)
                                {

                                    <th class=@String.Concat(clName,clNumber.ToString())>
                                        @Html.DisplayName(i.SeatClassName)
                                    </th>
                                    clNumber++;
                                }
                            }
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="column1">@Html.DisplayFor(modelItem => item.Plane.PlaneName)</td>
                                <td class="column2">@Html.DisplayFor(modelItem => item.Router.RouterName)</td>
                                <td class="column3">@Html.DisplayFor(modelItem => item.Dept_Time)</td>
                                <td class="column4"> @Html.DisplayFor(modelItem => item.Arr_Time)</td>
                                @{
                                    List<Price> Price = new List<Price>();
                                    Price = ViewBag.Price;
                                    List<DiscountDetail> Discount = new List<DiscountDetail>();
                                    Discount = ViewBag.Discount;
                                    int clNumber1 = 5;
                                    string clName1 = "column";
                                    foreach (var i in seatClasses)
                                    {
                                        List<AirlinesReservationSystem.ViewModels.InventoryTickets> quantityseat = new List<AirlinesReservationSystem.ViewModels.InventoryTickets>();
                                        quantityseat = ViewBag.Inventories;

                                        AirlinesReservationSystem.ViewModels.InventoryTickets inventoryTickets = new AirlinesReservationSystem.ViewModels.InventoryTickets();
                                        inventoryTickets = quantityseat.Where(x => x.FlightId == item.Flightid).Where(x => x.SeatClassId == i.SeatClassId).FirstOrDefault();

                                        List<Price> price = new List<Price>();
                                        price = Price.Where(x => x.FlightId == item.Flightid)
                                            .Where(x => x.SeatClassId == i.SeatClassId).ToList<Price>();

                                        List<DiscountDetail> discount = new List<DiscountDetail>();
                                        discount = Discount.Where(x => x.FlightId == item.Flightid)
                                            .ToList<DiscountDetail>();

                                        <td class=@String.Concat(clName1, clNumber1.ToString())>
                                            @{
                                                clNumber1++;
                                            }
                                            @{
                                                foreach (var x in price)
                                                {
                                                    foreach (var a in discount)
                                                    {
                                                        decimal PriceTotal = (decimal)(x.Price1 - (x.Price1 * a.Discount / 100));
                                                        <p style="color:mediumvioletred">Price: @PriceTotal.ToString()</p>
                                                        AirlinesReservationSystem.ViewModels.BookingViewModel Departflight = new AirlinesReservationSystem.ViewModels.BookingViewModel();


                                                        Departflight.DiscountId = a.DiscountId;
                                                        Departflight.PriceId = x.PriceId;
                                                        Departflight.Flightid = item.Flightid;
                                                        Departflight.SeatClassId = i.SeatClassId;

                                                        TempData["Depart" + item.Flightid + i.SeatClassId] = Departflight;
                                                        if (ViewBag.FlightArrival == null)
                                                        {
                                                            @Html.ActionLink(inventoryTickets.Inventory + " Seat left", "Booking", "Booking", new { FlightId = item.Flightid , SeatClassId = i.SeatClassId},null)
                                                        }
                                                        else
                                                        {
                                                            List<Flight> flightArrival = new List<Flight>();
                                                            flightArrival = ViewBag.FlightArrival;
                                                            TempData["FlightArrival"] = flightArrival;
                                                            @Html.ActionLink(inventoryTickets.Inventory + " Seat left", "ArrivalFlight", "Flights", new { FlightId = item.Flightid, SeatClassId = i.SeatClassId }, null)
                                                        }

                                                    }

                                                }
                                            }
                                        </td>

                                    }

                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Source/AirlinesReservationSystem/AirlinesReservationSystem/Views/Flights/NotHaveFlight.cshtml
@{
    ViewBag.Title = "NotHaveFlight";
   
}

<h2>Not Have Flight</h2>

@Html.ActionLink("Back Home", "Index", "Home")

Source/AirlinesReservationSystem/AirlinesReservationSystem/Views/Flights/_SearchFlight.cshtml
@model AirlinesReservationSystem.ViewModels.FlightViewModel

<script type="text/javascript">
    function Validate() {
        if (document.getElementById("from").value != document.getElementById("to").value) {
            if (document.getElementById("one-way").value == "OneWay") {
                if (document.getElementById("from").value == "" ||
                    document.getElementById("to").value == "" ||
                    document.getElementById("depart").value == ""
                ) {
                    alert("Please fill all the required fields!");
                    document.myForm.Name.focus();
                    return false;
                }
                return true;
            }
            if (document.getElementById("roundtrip").value == "Round") {
                    if (document.getElementById("from").value == "" ||
                        document.getElementById("to").value == "" ||
                        document.getElementById("depart").value == "" ||
                        document.getElementById("return").value == ""
                    ) {
                        alert("Please fill all the required fields!");
                        document.myForm.Name.focus();
                        return false;
                    }
                }
                else if (document.getElementById("depart").value > document.getElementById("return").value) {
                    document.getElementById("depart").value = new Date();
                    document.getElementById("return").value = new Date();
                    alert("Please choose the reasonable date!");
                    document.myForm.Name.focus();
                    return false;
                } 
            }
         else {
            alert("Please choose your reasonable destination!");
            document.myForm.Name.focus();
            return false;
        }  
    }
    
</script>

<div id="booking" class="container-fluid">
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-5" style="display:contents">
                    <div class="booking-cta">
                        <h1>Book your flight today</h1>
                    </div>
                </div>
                <div class="col-md-7 col-sm-7">
                    <div class="booking-form">
                        @using (Html.BeginForm("Index", "Flights", FormMethod.Post, new { @class = "ui large form", @onsubmit = "return(Validate());" }))
                        {
                            <div class="form-group">
                                <div class="form-checkbox">
                                    <label for="one-way">
                                        @Html.RadioButtonFor(model => model.Trip, "OneWay", new { @checked = true, @id = "one-way" })
                                        <span></span>One way
                                    </label>
                                    <label for="roundtrip">
                                        @Html.RadioButtonFor(model => model.Trip, "Round", new { @id = "roundtrip" })
                                        <span></span>Roundtrip
                                    </label>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <span class="form-label">Flying from</span>
                                        @Html.DropDownListFor(model => model.Location_Depart, (IEnumerable<SelectListItem>)TempData["DataDepart"], "Select City", htmlAttributes: new { @class = "form-control", @id = "from"})
                                        @Html.ValidationMessageFor(model => model.Location_Depart, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <span class="form-label">Flying to</span>
                                        @Html.DropDownListFor(model => model.Location_Arrival, (IEnumerable<SelectListItem>)TempData["DataArrival"], "Select City", htmlAttributes: new { @class = "form-control", @id = "to" })
                                        @Html.ValidationMessageFor(model => model.Location_Arrival, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <span class="form-label">Departing</span>
                                        @Html.EditorFor(model => model.Time_Depart, new { htmlAttributes = new { @class = "form-control", @type = "date", @id = "depart" } })
                                        @Html.ValidationMessageFor(model => model.Time_Depart, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <span class="form-label">Returning</span>
                                        @Html.EditorFor(model => model.Time_Arrival, new { htmlAttributes = new { @class = "form-control", @type = "date", @id = "return" } })
                                        @Html.ValidationMessageFor(model => model.Time_Arrival, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <span class="form-label">Adults (18+)</span>
                                        <select class="form-control" name="Adults" , id="Adults">
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                        </select>
                                        <span class="select-arrow"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <span class="form-label">Children (0-17)</span>
                                        <select class="form-control">
                                            <option>0</option>
                                            <option>1</option>
                                            <option>2</option>
                                        </select>
                                        <span class="select-arrow"></span>
                                    </div>
                                </div>

                            </div>
                            <div class="form-btn">
                                <button class="submit-btn">Show flights</button>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>

    </div>

    

        </div>
        <div style="clear:both; margin-top:80px">

        </div>